name: TFGIT Repository migration with User Input

on:
  workflow_dispatch:
    inputs:
      project_name:
        description: "Select the TFS Project"
        required: true
        type: choice
        options:
          - Healthcare-OETDApps
          - IM-ClientVertical-CAP_WEB_ENABLE
          - Healthcare-CLMCCE
          - Enterprise-FinanceE2EAutomation
          - Healthcare-CensusManager
          - Healthcare-Finance_IT
          - Healthcare-CSB
          - Specialty-CBH_ClaimsImage
          - Healthcare-PrePricingNetwork
          - Healthcare-ART
          - Healthcare-Treasury
          # Add more project names here

      repository_name:
        description: "Select the Repository"
        required: true
        type: choice
        options:
          - $/Healthcare-OETDApps
          - $/Healthcare-OETDApps/Velocity
          - $/Healthcare-OETDApps/GEM
          - $/IM-ClientVertical-CAP_WEB_ENABLE
          - $/Healthcare-CLMCCE/Cigna.CoreOps.VBS.CLMCEE.Router
          - $/Healthcare-CLMCCE/Cigna.CoreOps.VBS.CLMCCE.DWB.APCASC_Load
          - $/Enterprise-FinanceE2EAutomation/E2E-ERVTNNextGen
          - $/Healthcare-CensusManager/CensusManager
          - $/Healthcare-Finance_IT/Git-SICR
          - $/Healthcare-Finance_IT/Git-BCIP
          - $/Healthcare-Finance_IT/git-bcip-new
          - $/Healthcare-Finance_IT/Git-SOA
          - $/Healthcare-Finance_IT/GIT-SOARTD
          - $/Healthcare-Finance_IT/git-soa-new
          - $/Healthcare-CSB/csb-dll
          - $/Healthcare-CSB/csb-gov-broker-csb-api-LifeProWS
          - $/Specialty-CBH_ClaimsImage/Cigna.CBH.ClaimImageSearch.API
          - $/Specialty-CBH_ClaimsImage/Cigna.CBH.ClaimImageSearch.WebClient
          - $/Specialty-CBH_ClaimsImage/Cigna.CBH.OLAM.UI
          - $/Specialty-CBH_ClaimsImage/Cigna.CBH.Dashboard.UI
          - $/Specialty-CBH_ClaimsImage/Cigna.CBH.AutomatedSurvey.UI
          - $/Specialty-CBH_ClaimsImage/Cigna.CBH.ResourceNet.UI
          - $/Specialty-CBH_ClaimsImage/Cigna.CBH.Performance.UI
          - $/Specialty-CBH_ClaimsImage/Cigna.CBH.IntegratedReferral.UI
          - $/Specialty-CBH_ClaimsImage/Cigna.CBH.OnlineForms.UI
          - $/Healthcare-PrePricingNetwork/Cigna.Claim.PrePricingNetwork.Webclient
          - $/Healthcare-PrePricingNetwork/Cigna.Claim.PrePricingNetwork.Services
          - $/Healthcare-PrePricingNetwork/Cigna.PrePricing.UITests
          - $/Healthcare-PrePricingNetwork/Cigna.Prepricing.ARTTests
          - $/Healthcare-ART/ART-HealthCare
          - $/Healthcare-ART/ART-GIT
          - $/Healthcare-Treasury/DPAS-Test
          

          # Add more as needed

jobs:
  migrate-tfgit:    
    runs-on:
      group: TFS-Migration-Runner

    steps:    
      # - name: Disable SSL verification
      #   run: git config --global http.sslVerify false

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up environment variables
        shell: powershell
        run: |
          $env:TFS_PAT = "${{ secrets.TFS_PAT }}"
          $env:GITHUB_PAT = "${{ secrets.GH_PAT }}"
          [System.Environment]::SetEnvironmentVariable("GIT_TFS_PAT", $env:TFS_PAT, [System.EnvironmentVariableTarget]::User)

      - name: Generate input JSON file
        shell: powershell
        run: |
          $project = "${{ github.event.inputs.project_name }}"
          $repo = "${{ github.event.inputs.repository_name }}"
          $json = @(
            @{
              ProjectName = $project
              Repositories = @(
                @{
                  RepositoryName = $repo
                  RepositoryType = "GIT"
                }
              )
            }
          ) | ConvertTo-Json -Depth 4
          $json | Out-File -FilePath "./repo-migration/gitinput.json" -Encoding UTF8
          Write-Output "Generated JSON:"
          Write-Output $json

      - name: Execute migration script
        shell: powershell
        run: |
          $env:TFS_PAT = "${{ secrets.TFS_PAT }}"
          $env:GITHUB_PAT = "${{ secrets.GH_PAT }}"
          ./repo-migration/tfgit-to-github.ps1 -JsonFilePath "./repo-migration/gitinput.json" -TfsUrl "https://tfs.sys.cigna.com/tfs/DefaultCollection" -GitHubOrg "cigna-group"
