name: TFVC Repository migration with User Input

on:
  workflow_dispatch:
    inputs:
      project_name:
        description: "Select the TFS Project"
        required: true
        type: choice
        options:
          - Enterprise-Shared
          - Healthcare-Top60eProMacro
          - Healthcare-MHParityTool
          - Healthcare-CCS_ELIGIBILITY_ACE
          - Healthcare-LCRS
          - Healthcare-BCA_DenAdmin
          - Healthcare-CSB_App_New_Business
          # Add more project names here

      repository_name:
        description: "Select the Repository"
        required: true
        type: choice
        options:
          - $/Enterprise-Shared        
          - $/Enterprise-Shared/BuildProcessTemplates
          - $/Enterprise-Shared/CustomAssemblies
          - $/Enterprise-Shared/DeploymentsScripts
          - $/Enterprise-Shared/RMBuildProcessTemplates
          - $/Enterprise-Shared/WebDscModules
          - $/Healthcare-Top60eProMacro
          - $/Healthcare-Top60eProMacro/BuildProcessTemplates
          - $/Healthcare-Top60eProMacro/Development
          - $/Healthcare-Top60eProMacro/Main
          - $/Healthcare-Top60eProMacro/Release
          - $/Healthcare-MHParityTool
          - $/Healthcare-MHParityTool/BenefitExtractor
          - $/Healthcare-MHParityTool/Cigna.SUW.MHParityTool
          - $/Healthcare-MHParityTool/Database
          - $/Healthcare-CSB_App_New_Business
          - $/Healthcare-CSB_App_New_Business/BuildProcessTemplates
          - $/Healthcare-CSB_App_New_Business/Development
          - $/Healthcare-CSB_App_New_Business/Healthcare-CSB_Framework
          - $/Healthcare-CSB_App_New_Business/Main
          - $/Healthcare-CSB_App_New_Business/Release
          - $/Healthcare-LCRS
          - $/Healthcare-LCRS/BuildProcessTemplates
          - $/Healthcare-LCRS/Development
          - $/Healthcare-LCRS/Main
          - $/Healthcare-LCRS/Release        
          # Add more as needed

jobs:
  migrate-tfvc:    
    runs-on:
      group: TFS-Migration-Runner

    steps:    
    
      - name: Disable SSL verification
        run: git config --global http.sslVerify false

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up environment variables
        shell: powershell
        run: |
          $env:TFS_PAT = "${{ secrets.TFS_PAT }}"
          $env:GITHUB_PAT = "${{ secrets.GH_PAT }}"
          [System.Environment]::SetEnvironmentVariable("GIT_TFS_PAT", $env:TFS_PAT, [System.EnvironmentVariableTarget]::User)

      - name: Generate input JSON file
        shell: powershell
        run: |
          $project = "${{ github.event.inputs.project_name }}"
          $repo = "${{ github.event.inputs.repository_name }}"
          $json = @(
            @{
              ProjectName = $project
              Repositories = @(
                @{
                  RepositoryName = $repo
                  RepositoryType = "TFVC"
                }
              )
            }
          ) | ConvertTo-Json -Depth 4
          $json | Out-File -FilePath "./repo-migration/input.json" -Encoding UTF8
          Write-Output "Generated JSON:"
          Write-Output $json

      - name: Execute migration script
        shell: powershell
        run: |
          $env:TFS_PAT = "${{ secrets.TFS_PAT }}"
          $env:GITHUB_PAT = "${{ secrets.GH_PAT }}"
          ./repo-migration/tfvc-to-github.ps1 -JsonFilePath "./repo-migration/input.json" -TfsUrl "https://tfs.sys.cigna.com/tfs/DefaultCollection" -GitHubOrg "cigna-group"
